"""add track classification

Revision ID: 8d2437af9b80
Revises: d22a0d4bfe2e
Create Date: 2026-09-09 16:07:33.237219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2437af9b80'
down_revision: Union[str, Sequence[str], None] = 'd22a0d4bfe2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('classification', sa.String(length=30), server_default='UNKNOWN', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'classification')
    # ### end Alembic commands ###
