"""add track quality

Revision ID: 9a4729a1683f
Revises: db2ba2ab88ef
Create Date: 2026-09-11 14:16:11.029415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4729a1683f'
down_revision: Union[str, Sequence[str], None] = 'db2ba2ab88ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('quality', sa.Float(), server_default=sa.text('0.5'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'quality')
    # ### end Alembic commands ###
